apiVersion: apps/v1
kind: Deployment
metadata:
  name: jacksonudagram
  labels:
    app: jacksonudagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jacksonudagram
  template:
    metadata:
      labels:
        app: jackosnudagram
    spec:
      containers:
      - name: jacksonudagram
        image: jacksonmike/udacity-c3-deployment
        ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDeplaySeconds: 3
        periodSeconds: 3