apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: jacksonudagram
  AWS_PROFILE: jacksonudagram
  AWS_REGION: us-east-2
  JWT_SECRET: jacksonudagram
  POSTGRESS_DB: jacksonudagram
  POSTGRESS_HOST: jacksonudagram.cm4xlcca34ef.us-east-2.rds.amazonaws.com
  URL: http://localhost:8100  
metadata:
  name: env-config
  